//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giris
    {
        public int ID { get; set; }
        public string kulAd { get; set; }
        public string sifre { get; set; }
    }
}
