//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int siparisID { get; set; }
        public Nullable<int> siparisUrun { get; set; }
        public string siparisIsim { get; set; }
        public string siparisAdet { get; set; }
        public Nullable<System.DateTime> siparisZaman { get; set; }
        public Nullable<int> siparisMasa { get; set; }
        public string siparisDurum { get; set; }
        public Nullable<int> siparisFiyat { get; set; }
    
        public virtual Urun Urun { get; set; }
        public virtual Masa Masa { get; set; }
    }
}
